# Site settings
title: Zhuang Xu - Desenvolvedor
description: A blog about lorem ipsum dolor sit amet
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xuzhuang.art" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zhuang Xu
user_description: Anon Developer at Lorem Ipsum Dolor
email:
twitter_username:
github_username:  zhuangxu0
gplus_username:
disqus_username:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
